### ISSUE TITLE
Hero section separator still overlapping on small screens

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/website#10]
The separator is overlapping on mobile landscape mode. 
The PR at #7 by @guytepper didn't solve it completely. 

![Screenshot_20201210-230631](https://user-images.githubusercontent.com/20182642/101874748-22338d80-3b92-11eb-968b-da8ed445e43e.jpg)

**Comment by adityatelange** [comment]
@ITAYC0HEN try changing https://github.com/rizinorg/website/blob/6facbbdcf983536c46b79b36e6a4055a7999aa64/assets/css/custom/rizin.css#L439 to 500px

**Comment by ITAYC0HEN** [comment]
Thanks @adityatelange ! <3
Fixed by d030f81
