### ISSUE TITLE
Provide links and page with Release information

### ISSUE THREAD

**Issue by XVilka** [rizinorg/website#32]
We should have good "Download" and release information pages.
Thus, the need to link directly to GitHub is unnecessary.

For example, Cutter site has "#release-notes" anchor, but it's embedded in the main page, which might be undesirable, and probably deserves its own page.

**Comment by vext01** [comment]
https://github.com/rizinorg/website/pull/36 addresses some of this.

**Comment by XVilka** [comment]
Solved by: https://rizin.re/install/
If you think something is missing - feel free to write in this issue or open a new one.
