### ISSUE TITLE
[Question] About the format of the posts

### ISSUE THREAD

**Issue by mzfr** [rizinorg/website#6]
Hey,

I noticed that on your blog posts the text is not centralized meaning its covering the whole screen. But the default setup of the PaperMod theme have the posts in the centralized form.

__Centralized Form__

![image](https://user-images.githubusercontent.com/16623935/101540796-8a357880-39c6-11eb-8785-d601f4a3e0e7.png)

This is what I am calling the centralized form, the text is only in the center. But your blog posts looks like:

![image](https://user-images.githubusercontent.com/16623935/101541060-dbde0300-39c6-11eb-8c59-bef587444491.png)

Not just in center but from left to right covering the screen.

So I wanted to ask how did you guys changed this? Did you had to modify any template? If yes then can you please tell me which one.

Thanks

**Comment by ITAYC0HEN** [comment]
Hey @mzfr! Yes, we used PaperMod as a base theme and extended it to create the website for Rizin. No hacks involved, you can see that PaperMod supports extending the theme out of the box.

Extending `head` adn `footer`: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-how-to/#custom-head--footer

In the line on `head.html` you can see that PaperMod loads all the CSS files reside in assets/css
https://github.com/adityatelange/hugo-PaperMod/blob/11c32302144c0f91734525bbe1f1d11ed1a16022/layouts/partials/head.html#L24

On this projects' Readme you can see a directory tree with some comments I put to ease the work for people who want to contribute
Enjoy!
